name = "postanos-scheduler"
main = "postcard-scheduler.ts"
compatibility_date = "2024-01-01"

# Cron trigger - runs daily at 9 AM UTC (1 AM PST / 4 AM EST)
[triggers]
crons = ["0 9 * * *"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "postanos-prod"
database_id = "YOUR_DATABASE_ID" # Replace with the actual D1 database ID you copied

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[vars]
LOB_API_VERSION = "2024-01-01"
LOB_SANDBOX_MODE = "true" # Set to "false" in production

# Secrets (set via: wrangler secret put <KEY>)
# LOB_API_KEY
# ONESIGNAL_APP_ID (optional)
# ONESIGNAL_API_KEY (optional)
# TWILIO_ACCOUNT_SID (optional)
# TWILIO_AUTH_TOKEN (optional)
# TWILIO_FROM_NUMBER (optional)

# Optional R2 bucket binding for images
# [[r2_buckets]]
# binding = "IMAGES_BUCKET"
# bucket_name = "postanos-images"